#!/usr/bin/env python3
"""
TR ASCII -> Diacritics converter (v2, safer placeholder logic).

Single-pass placeholder approach:
- Scan entire file text.
- Identify protected regions (URLs, href/src/class/id/style/data-* attrs, imports,
  comments, script-tag contents, absolute-path slug strings).
- Replace protected regions with unique sentinel tokens using a SINGLE combined regex
  (no nested multi-pass substitution).
- Apply word-level TR conversion on the remaining masked text.
- Restore sentinels.

Tokens use chars unlikely to appear in source: \u0001...\u0002 with index.
"""
import re
from pathlib import Path

ROOT = Path(r"C:\Users\User\Projects\Pratik Yapay Zeka\pratik-yapay-zeka-astro")

TARGETS = [
    "src/pages/make-vs-zapier-vs-n8n.astro",
    "src/pages/vaka-calismalari/acilsatis.astro",
    "src/pages/vaka-calismalari/car-studio-ai.astro",
    "src/pages/vaka-calismalari/cemkimsan.astro",
    "src/pages/vaka-calismalari/dkm-coach-bilge.astro",
    "src/pages/vaka-calismalari/erpa-teknoloji.astro",
    "src/pages/vaka-calismalari/salevium.astro",
    "src/pages/crm-programi.astro",
    "src/pages/whatsapp-ve-siparis-botlari.astro",
    "src/pages/on-muhasebe-ve-fatura.astro",
    "src/pages/teklif-hazirlama-programi.astro",
    "src/pages/b2b-musteri-bulma.astro",
    "src/pages/marketing-otomasyonu.astro",
    "src/pages/kurumsal-e-posta-otomasyonu.astro",
    "src/pages/yapay-zeka-chatbot.astro",
    "src/pages/e-ticaret-ve-pazaryeri-otomasyonu.astro",
    "src/pages/b2b-musteri-takip-ve-plasiyer.astro",
    "src/pages/bordro-hesaplama.astro",
    "src/pages/kidem-tazminati-hesaplama.astro",
    "src/pages/ihbar-tazminati-hesaplama.astro",
    "src/pages/isverene-maliyet-hesaplama.astro",
    "src/pages/yillik-izin-ucreti-hesaplama.astro",
    "src/pages/fazla-mesai-hesaplama.astro",
    "src/pages/kdv-hesaplama.astro",
    "src/pages/vergi-iadesi-hesaplama.astro",
    "src/pages/gecikme-zammi-hesaplama.astro",
    "src/pages/maas-hesaplama-motoru.astro",
    "src/pages/brutten-nete.astro",
    "src/pages/arac-deger-kaybi-hesaplama.astro",
    "src/pages/e-fatura-kesme-programi.astro",
    "src/pages/e-arsiv-portali.astro",
    "src/pages/e-beyanname.astro",
    "src/pages/defter-beyan.astro",
    "src/pages/cari-hesap-ekstresi.astro",
    "src/pages/mutabakat-mektubu.astro",
    "src/pages/acik-fatura-kapali-fatura.astro",
    "src/pages/ticaret-sicil-gazetesi.astro",
    "src/pages/sgk-hizmet-dokumu.astro",
    "src/pages/stok-takibi-programi.astro",
    "src/pages/cozumler/index.astro",
    "src/layouts/SolutionLayout.astro",
    "src/layouts/CaseStudyLayout.astro",
    "src/layouts/CalculatorLayout.astro",
    "src/components/LeadPathways.astro",
]

WORD_MAP_RAW = {
    # Multi-word phrases — matched first
    "kidem tazminati": "kıdem tazminatı",
    "ihbar tazminati": "ihbar tazminatı",
    "iscilik maliyeti": "işçilik maliyeti",
    "on muhasebe": "ön muhasebe",
    "maas hesaplama": "maaş hesaplama",
    "musteri takip": "müşteri takip",
    "musteri takibi": "müşteri takibi",
    "surec otomasyonu": "süreç otomasyonu",
    "vaka calismalari": "vaka çalışmaları",
    "vaka calismalarimiz": "vaka çalışmalarımız",
    # Single words
    "musteri": "müşteri",
    "musteriler": "müşteriler",
    "musterinin": "müşterinin",
    "musteriye": "müşteriye",
    "musteriden": "müşteriden",
    "sirket": "şirket",
    "sirketler": "şirketler",
    "sirketin": "şirketin",
    "sirketi": "şirketi",
    "sirketimiz": "şirketimiz",
    "cozum": "çözüm",
    "cozumu": "çözümü",
    "cozumler": "çözümler",
    "cozumleri": "çözümleri",
    "cozumlerimiz": "çözümlerimiz",
    "cozume": "çözüme",
    "surec": "süreç",
    "sureci": "süreci",
    "surecler": "süreçler",
    "surecleri": "süreçleri",
    "sureclerini": "süreçlerini",
    "sureclerinizi": "süreçlerinizi",
    "sure": "süre",
    "suresi": "süresi",
    "suresinde": "süresinde",
    "surekli": "sürekli",
    "surer": "sürer",
    "kidem": "kıdem",
    "iscilik": "işçilik",
    "isci": "işçi",
    "isciler": "işçiler",
    "iscinin": "işçinin",
    "iscileri": "işçileri",
    "hakkimizda": "hakkımızda",
    "iletisim": "iletişim",
    "basari": "başarı",
    "basarili": "başarılı",
    "basarisi": "başarısı",
    "basarilari": "başarıları",
    "isletme": "işletme",
    "isletmeler": "işletmeler",
    "isletmeniz": "işletmeniz",
    "isletmesi": "işletmesi",
    "isletmesinde": "işletmesinde",
    "isletmelerin": "işletmelerin",
    "yonetim": "yönetim",
    "yonetimi": "yönetimi",
    "yoneten": "yöneten",
    "yonetici": "yönetici",
    "yoneticisi": "yöneticisi",
    "urun": "ürün",
    "urunler": "ürünler",
    "urunun": "ürünün",
    "urunu": "ürünü",
    "uretim": "üretim",
    "uretimi": "üretimi",
    "uretimde": "üretimde",
    "uretici": "üretici",
    "satis": "satış",
    "satisi": "satışı",
    "satislar": "satışlar",
    "satislari": "satışları",
    "satislarinizi": "satışlarınızı",
    "siparis": "sipariş",
    "siparisi": "siparişi",
    "siparisler": "siparişler",
    "siparisleri": "siparişleri",
    "siparislerinizi": "siparişlerinizi",
    "donusum": "dönüşüm",
    "donusumu": "dönüşümü",
    "donusumler": "dönüşümler",
    "calisan": "çalışan",
    "calisanlar": "çalışanlar",
    "calisanlarin": "çalışanların",
    "calisma": "çalışma",
    "calismalar": "çalışmalar",
    "calismalari": "çalışmaları",
    "calismalarimiz": "çalışmalarımız",
    "calistigi": "çalıştığı",
    "calisiyor": "çalışıyor",
    "ogrenme": "öğrenme",
    "ogrenen": "öğrenen",
    "ogrenci": "öğrenci",
    "kucuk": "küçük",
    "saglik": "sağlık",
    "saglikli": "sağlıklı",
    "tazminati": "tazminatı",
    "programi": "programı",
    "gorunum": "görünüm",
    "gorme": "görme",
    "goruntu": "görüntü",
    "goruntuleme": "görüntüleme",
    "gorunur": "görünür",
    "gorunurluk": "görünürlük",
    "gorunurlugu": "görünürlüğü",
    "guvenlik": "güvenlik",
    "guvenli": "güvenli",
    "ucret": "ücret",
    "ucretli": "ücretli",
    "ucretsiz": "ücretsiz",
    "ucreti": "ücreti",
    "ozel": "özel",
    "ozelligi": "özelliği",
    "ozellik": "özellik",
    "ozellikler": "özellikler",
    "ozellikle": "özellikle",
    "once": "önce",
    "oncelik": "öncelik",
    "oncelikli": "öncelikli",
    "otomatiklestirin": "otomatikleştirin",
    "otomatiklestirme": "otomatikleştirme",
    "otomatiklestirilmis": "otomatikleştirilmiş",
    "onerisi": "önerisi",
    "oneri": "öneri",
    "tum": "tüm",
    "tumu": "tümü",
    "tumunu": "tümünü",
    "gun": "gün",
    "gunluk": "günlük",
    "guncel": "güncel",
    "guncellenen": "güncellenen",
    "guncelleme": "güncelleme",
    "guclu": "güçlü",
    "dusuk": "düşük",
    "dusunebilen": "düşünebilen",
    "dusun": "düşün",
    "dusunce": "düşünce",
    "dusunur": "düşünür",
    "mumkun": "mümkün",
    "mukemmel": "mükemmel",
    "muhendislik": "mühendislik",
    "muhendis": "mühendis",
    "butce": "bütçe",
    "butceye": "bütçeye",
    "butun": "bütün",
    "hizli": "hızlı",
    "hizlica": "hızlıca",
    "hizlanan": "hızlanan",
    "cikti": "çıktı",
    "cikan": "çıkan",
    "cikar": "çıkar",
    "cikis": "çıkış",
    "cikisi": "çıkışı",
    "cikislar": "çıkışlar",
    "cikislarin": "çıkışların",
    "cevir": "çevir",
    "cevrim": "çevrim",
    "cevrimici": "çevrimiçi",
    "cesit": "çeşit",
    "cesitli": "çeşitli",
    "coklu": "çoklu",
    "cok": "çok",
    "cogu": "çoğu",
    "cogunlukla": "çoğunlukla",
    "acilan": "açılan",
    "acik": "açık",
    "acilis": "açılış",
    "aciklama": "açıklama",
    "aciklamasi": "açıklaması",
    "agirlik": "ağırlık",
    "islem": "işlem",
    "islemleri": "işlemleri",
    "islemi": "işlemi",
    "islemler": "işlemler",
    "islemeye": "işlemeye",
    "isbirligi": "işbirliği",
    "isleyis": "işleyiş",
    "isimiz": "işimiz",
    "isiniz": "işiniz",
    "isyeri": "işyeri",
    "kisa": "kısa",
    "kisit": "kısıt",
    "kisitli": "kısıtlı",
    "kisim": "kısım",
    "kisi": "kişi",
    "kisiler": "kişiler",
    "kisisel": "kişisel",
    "kidemli": "kıdemli",
    "disaridan": "dışarıdan",
    "disari": "dışarı",
    "disardan": "dışardan",
    "disinda": "dışında",
    "degerlendirme": "değerlendirme",
    "deger": "değer",
    "degeri": "değeri",
    "degisken": "değişken",
    "degisim": "değişim",
    "degisimi": "değişimi",
    "degisiklik": "değişiklik",
    "degisiklikler": "değişiklikler",
    "gelistirici": "geliştirici",
    "gelistirme": "geliştirme",
    "gelistiren": "geliştiren",
    "gerceklestir": "gerçekleştir",
    "gercek": "gerçek",
    "gercekten": "gerçekten",
    "gecis": "geçiş",
    "gecmis": "geçmiş",
    "gecerli": "geçerli",
    "gorev": "görev",
    "gorevi": "görevi",
    "gorevli": "görevli",
    "gorusme": "görüşme",
    "goruselim": "görüşelim",
    "gorusebilir": "görüşebilir",
    "gonder": "gönder",
    "gonderim": "gönderim",
    "gonderilen": "gönderilen",
    "gonderme": "gönderme",
    "gunde": "günde",
    "gunumuz": "günümüz",
    "kurulus": "kuruluş",
    "yukle": "yükle",
    "yuklenir": "yüklenir",
    "yukleme": "yükleme",
    "yuksek": "yüksek",
    "yururluk": "yürürlük",
    "yuzde": "yüzde",
    "cozulur": "çözülür",
    "cozumlemek": "çözümlemek",
    "cozumleme": "çözümleme",
    "azaltti": "azalttı",
    "artirdi": "artırdı",
    "artirin": "artırın",
    "artis": "artış",
    "artti": "arttı",
    "saglar": "sağlar",
    "saglayan": "sağlayan",
    "sagladi": "sağladı",
    "saglayin": "sağlayın",
    "saglanir": "sağlanır",
    "farki": "farkı",
    "farkli": "farklı",
    "tasarlanmis": "tasarlanmış",
    "tasarim": "tasarım",
    "tasarimi": "tasarımı",
    "karsilasma": "karşılaşma",
    "karsilastirma": "karşılaştırma",
    "karsilik": "karşılık",
    "karsi": "karşı",
    "karsisinda": "karşısında",
    "aksam": "akşam",
    "teslimi": "teslimi",
    "teslimati": "teslimatı",
    "isveren": "işveren",
    "isverene": "işverene",
    "isverenin": "işverenin",
    "yillik": "yıllık",
    "brut": "brüt",
    "brutten": "brütten",
    "bruttan": "brüttan",
    "maas": "maaş",
    "maasi": "maaşı",
    "maasli": "maaşlı",
    "aylik": "aylık",
    "hesabi": "hesabı",
    "dogrulanmis": "doğrulanmış",
    "dogru": "doğru",
    "dogruca": "doğruca",
    "dogrulugu": "doğruluğu",
    "sozlesme": "sözleşme",
    "sozlesmeli": "sözleşmeli",
    "soz": "söz",
    "vakalari": "vakaları",
    "hazirlama": "hazırlama",
    "hazirlanan": "hazırlanan",
    "hazirlanir": "hazırlanır",
    "hazirladik": "hazırladık",
    "hazirligi": "hazırlığı",
    "hazirlik": "hazırlık",
    "dokumu": "dökümü",
    "takibi": "takibi",
    "zammi": "zammı",
    "iadesi": "iadesi",
    "arac": "araç",
    "kaybi": "kaybı",
    "cikmasi": "çıkması",
    "cikmis": "çıkmış",
    "cikinca": "çıkınca",
    "icin": "için",
    "icinde": "içinde",
    "icerik": "içerik",
    "icerigi": "içeriği",
    "icerir": "içerir",
    "icerisinde": "içerisinde",
    "ucun": "üçün",
    "uc": "üç",
    "uye": "üye",
    "uyesi": "üyesi",
    "zorluk": "zorluk",
    "olcu": "ölçü",
    "olcekleme": "ölçekleme",
    "olceklenme": "ölçeklenme",
    "tuketir": "tüketir",
    "tuketim": "tüketim",
    "tuketiyor": "tüketiyor",
    "yanitsiz": "yanıtsız",
    "yanit": "yanıt",
    "yanlis": "yanlış",
    "yaklasim": "yaklaşım",
    "yaklasimi": "yaklaşımı",
    "yaklasik": "yaklaşık",
    "baglanti": "bağlantı",
    "baglantisi": "bağlantısı",
    "baglan": "bağlan",
    "baslangic": "başlangıç",
    "baslar": "başlar",
    "baslat": "başlat",
    "baslatan": "başlatan",
    "basladi": "başladı",
    "baslama": "başlama",
    "baslayan": "başlayan",
    "kurulum": "kurulum",
    "kurulumu": "kurulumu",
    "sonuc": "sonuç",
    "sonucu": "sonucu",
    "sonuclar": "sonuçlar",
    "sonuclari": "sonuçları",
    "akis": "akış",
    "akisi": "akışı",
    "akislari": "akışları",
    "akisin": "akışın",
    "akisinda": "akışında",
    "bilgisi": "bilgisi",
    "bilgileri": "bilgileri",
    "bilgilerin": "bilgilerin",
    "bilgiyi": "bilgiyi",
    "birakin": "bırakın",
    "birakti": "bıraktı",
    "birak": "bırak",
    "zamaninda": "zamanında",
    "zamanin": "zamanın",
    "cizgi": "çizgi",
    "cizgisi": "çizgisi",
    "sirali": "sıralı",
    "sirayla": "sırayla",
    "sira": "sıra",
    "sinir": "sınır",
    "siniri": "sınırı",
    "sinirinda": "sınırında",
    "sinirlari": "sınırları",
    "sinirsiz": "sınırsız",
    "sinifi": "sınıfı",
    "sinif": "sınıf",
    "darbogaz": "darboğaz",
    "daginik": "dağınık",
    "netlestirmek": "netleştirmek",
    "netlestirilmesi": "netleştirilmesi",
    "netlesir": "netleşir",
    "onay": "onay",
    "onayi": "onayı",
    "yipraniyor": "yıpranıyor",
    "yipranma": "yıpranma",
    "yipratic": "yıpratıc",
    "duzenli": "düzenli",
    "duzen": "düzen",
    "duzgun": "düzgün",
    "duzey": "düzey",
    "duzeyi": "düzeyi",
    "duzenleme": "düzenleme",
    "duzenlendigi": "düzenlendiği",
    "duzenleyen": "düzenleyen",
    "duzeltme": "düzeltme",
    "duzeltilmis": "düzeltilmiş",
    "tahakkuk": "tahakkuk",
    "odeme": "ödeme",
    "odemesi": "ödemesi",
    "odemeleri": "ödemeleri",
    "odeyen": "ödeyen",
    "odenmesi": "ödenmesi",
    "odenen": "ödenen",
    "evraklari": "evrakları",
    "evrak": "evrak",
    "buyuk": "büyük",
    "buyume": "büyüme",
    "buyumesi": "büyümesi",
    "buyumekte": "büyümekte",
    "buyuyen": "büyüyen",
    "rakam": "rakam",
    "rakami": "rakamı",
    "cesitli": "çeşitli",
    "hukuki": "hukuki",
    "kasit": "kasıt",
    "kasitli": "kasıtlı",
    "iliski": "ilişki",
    "iliskili": "ilişkili",
    "iliskin": "ilişkin",
    "iliskisi": "ilişkisi",
    "ilgili": "ilgili",
    "surprizler": "sürprizler",
    "surpriz": "sürpriz",
    "usuller": "usuller",
    "uslup": "üslup",
    "uretken": "üretken",
    "uretkenlige": "üretkenliğe",
    "dunyasinda": "dünyasında",
    "dunya": "dünya",
    "tutarsiz": "tutarsız",
    "tutarli": "tutarlı",
    "tutar": "tutar",
    "tutari": "tutarı",
    "ustel": "üstel",
    "ustun": "üstün",
    "uzerine": "üzerine",
    "uzerinde": "üzerinde",
    "uzerinden": "üzerinden",
    "sekilde": "şekilde",
    "sekil": "şekil",
    "sekli": "şekli",
    "sabit": "sabit",
    "sartli": "şartlı",
    "sart": "şart",
    "sarti": "şartı",
    "saglayici": "sağlayıcı",
    "saglayan": "sağlayan",
    "saglayarak": "sağlayarak",
    "saglayacak": "sağlayacak",
    "kolaylik": "kolaylık",
    "kolayca": "kolayca",
    "kapali": "kapalı",
    "acik": "açık",
    "gozden": "gözden",
    "goz": "göz",
    "kuruldu": "kuruldu",
    "kurulan": "kurulan",
    "mukemmellik": "mükemmellik",
    "pazarlama": "pazarlama",
    # common typo-like
    "yonetme": "yönetme",
    "yoneten": "yöneten",
    "gecirmek": "geçirmek",
    "gecisi": "geçişi",
    "ihtiyaci": "ihtiyacı",
    "ihtiyaclari": "ihtiyaçları",
    "aktarimi": "aktarımı",
    "aktarma": "aktarma",
    "duzeltilmeli": "düzeltilmeli",
    "duzgunce": "düzgünce",
    "cagri": "çağrı",
    "cagrisi": "çağrısı",
    "cagrilari": "çağrıları",
    "yapilabilir": "yapılabilir",
    "yapildi": "yapıldı",
    "yapilan": "yapılan",
    "yapildigi": "yapıldığı",
    "yapilir": "yapılır",
    "yapilan": "yapılan",
    "yapildigini": "yapıldığını",
    "yapi": "yapı",
    "yapilanma": "yapılanma",
    "yapisi": "yapısı",
    "yapisal": "yapısal",
    "degil": "değil",
    "degildir": "değildir",
    "donem": "dönem",
    "donemi": "dönemi",
    "donemde": "dönemde",
    "tarafi": "tarafı",
    "taraflari": "tarafları",
    "kar": "kâr",  # skip: ambiguous
    # problematic duplicates resolved by being mapped above; below are unique additions
    "tuketimi": "tüketimi",
    "tuketen": "tüketen",
    "olur": "olur",  # no-op placeholder to keep pattern safe
    "aktariyor": "aktarıyor",
    "sozdizimi": "sözdizimi",
    "cokertmemesi": "çökertmemesi",
    "coker": "çöker",
    # Extended common words from review
    "hayir": "hayır",
    "yonetin": "yönetin",
    "yonet": "yönet",
    "surecinin": "sürecinin",
    "surecinde": "sürecinde",
    "surecin": "sürecin",
    "surecine": "sürecine",
    "formul": "formül",
    "parcasi": "parçası",
    "parca": "parça",
    "parcalar": "parçalar",
    "ihtiyacinin": "ihtiyacının",
    "ihtiyaci": "ihtiyacı",
    "gerektigini": "gerektiğini",
    "gerektigi": "gerektiği",
    "gerektirir": "gerektirir",
    "ilerletmektir": "ilerletmektir",
    "ilerleyen": "ilerleyen",
    "gormek": "görmek",
    "gorur": "görür",
    "gorunur": "görünür",
    "toparlamak": "toparlamak",
    "toparlanmasi": "toparlanması",
    "zorlandigi": "zorlandığı",
    "zorlar": "zorlar",
    "kalabilir": "kalabilir",
    "calisma": "çalışma",
    "calismayi": "çalışmayı",
    "calismakta": "çalışmakta",
    "akmiyorsa": "akmıyorsa",
    "alinmasi": "alınması",
    "alinir": "alınır",
    "alinma": "alınma",
    "anlatir": "anlatır",
    "anlattiginizda": "anlattığınızda",
    "baslamak": "başlamak",
    "beldir": "bellidir",
    "belirleyelim": "belirleyelim",
    "belirleyen": "belirleyen",
    "belirli": "belirli",
    "beldir": "bellidir",
    "netlesir": "netleşir",
    "hazirlanacagi": "hazırlanacağı",
    "hazirlanmak": "hazırlanmak",
    "hazirlanirken": "hazırlanırken",
    "hazirlandi": "hazırlandı",
    "kurabildiklerini": "kurabildiklerini",
    "kurulabilir": "kurulabilir",
    "cikis": "çıkış",
    "cikisi": "çıkışı",
    "cikisa": "çıkışa",
    "hizli": "hızlı",
    "verecegi": "vereceği",
    "onceden": "önceden",
    "oncelikle": "öncelikle",
    "birkac": "birkaç",
    "kac": "kaç",
    "yipratici": "yıpratıcı",
    "sifir": "sıfır",
    "sifirdan": "sıfırdan",
    "seferinde": "seferinde",
    "tikandigini": "tıkandığını",
    "tikali": "tıkalı",
    "dogus": "doğuş",
    "dogar": "doğar",
    "ilk": "ilk",
    "kagit": "kâğıt",
    "imza": "imza",
    "vakaya": "vakaya",
    "kazanir": "kazanır",
    "kazaniyor": "kazanıyor",
    "kazandigi": "kazandığı",
    "yasakli": "yasaklı",
    "asiri": "aşırı",
    "asil": "asıl",
    "azaltir": "azaltır",
    "onerir": "önerir",
    "onermek": "önermek",
    "sunar": "sunar",
    "sunuyor": "sunuyor",
    "olcuyor": "ölçüyor",
    "gercekliktir": "gerçekliktir",
    "saglamak": "sağlamak",
    "saglayabilir": "sağlayabilir",
    "rahatlik": "rahatlık",
    "rahatca": "rahatça",
    "dakik": "dakik",
    "dakikalik": "dakikalık",
    "acilis": "açılış",
    "acik": "açık",
    "acan": "açan",
    "agir": "ağır",
    "aga": "ağa",
    "artik": "artık",
    "atilabilecek": "atılabilecek",
    "adim": "adım",
    "adimi": "adımı",
    "adimlari": "adımları",
    "adimlarini": "adımlarını",
    "adimlar": "adımlar",
}
# Remove no-ops (key == value)
WORD_MAP = {k.lower(): v for k, v in WORD_MAP_RAW.items() if k.lower() != v}

# Sorted longest-first to prefer multi-word / longer keys
SORTED_KEYS = sorted(WORD_MAP.keys(), key=lambda x: -len(x))
WORD_PATTERN = re.compile(r'(?<![A-Za-z0-9])(' + '|'.join(re.escape(k) for k in SORTED_KEYS) + r')(?![A-Za-z0-9])',
                          re.IGNORECASE)

def preserve_case(original: str, replacement: str) -> str:
    if original.isupper() and len(original) > 1:
        return replacement.upper()
    # capitalize word-by-word (handles multi-word keys)
    if original[0].isupper():
        # Apply title-case per word only to non-stopword segments; simpler: capitalize first letter of each space-separated token
        parts_o = original.split(' ')
        parts_r = replacement.split(' ')
        if len(parts_o) == len(parts_r):
            out = []
            for po, pr in zip(parts_o, parts_r):
                if po and po[0].isupper() and pr:
                    out.append(pr[0].upper() + pr[1:])
                else:
                    out.append(pr)
            return ' '.join(out)
        return replacement[0].upper() + replacement[1:]
    return replacement

def apply_word_map(text: str) -> str:
    def repl(m):
        orig = m.group(1)
        key = orig.lower()
        if key in WORD_MAP:
            return preserve_case(orig, WORD_MAP[key])
        return orig
    return WORD_PATTERN.sub(repl, text)

# Protected region regex — combined into ONE pattern so matches are disjoint.
# Order: most specific first.
PROTECT_PATTERNS = [
    # Script tags (entire block) - careful: we do want JSON schema values converted inside ld+json,
    # so only skip script blocks that are NOT ld+json.
    (r'<script(?![^>]*application/ld\+json)[^>]*>.*?</script>', 'SCRIPT'),
    # Style blocks
    (r'<style[^>]*>.*?</style>', 'STYLE'),
    # HTML comments
    (r'<!--.*?-->', 'HTMLCMT'),
    # JS block comments
    (r'/\*[\s\S]*?\*/', 'JSBCMT'),
    # Import / from lines (up to end of line)
    (r'^[ \t]*(?:import|from)[ \t][^\n]*', 'IMPORT'),
    # Single-line // comments (end of line) — but avoid URLs http://
    (r'(?<![:/])//[^\n]*', 'JSCMT'),
    # URL string literals (double, single, backtick)
    (r'"https?://[^"]*"', 'URLD'),
    (r"'https?://[^']*'", 'URLS'),
    (r'`https?://[^`]*`', 'URLB'),
    # Absolute path slug strings (e.g. "/cozumler/", "/kidem-tazminati-hesaplama/")
    (r'"/[a-zA-Z0-9][a-zA-Z0-9\-/_]*/?"', 'SLUGD'),
    (r"'/[a-zA-Z0-9][a-zA-Z0-9\-/_]*/?'", 'SLUGS'),
    # Attribute values: href, src, action, formAction, class, className, id, style, name(attr),
    # slot, data-*, aria-controls, aria-describedby, aria-labelledby, rel, type, property,
    # as, crossorigin, integrity, loading, decoding, sizes, media
    (r'(?:href|src|action|formAction|class|className|id|style|slot|rel|type|property|as|crossorigin|integrity|loading|decoding|sizes|media|data-[a-zA-Z\-]+|aria-controls|aria-describedby|aria-labelledby|aria-hidden|aria-expanded|tabindex|role|set:html|is:raw|define:vars)\s*=\s*"[^"]*"', 'ATTRD'),
    (r"(?:href|src|action|formAction|class|className|id|style|slot|rel|type|property|as|crossorigin|integrity|loading|decoding|sizes|media|data-[a-zA-Z\-]+|aria-controls|aria-describedby|aria-labelledby|aria-hidden|aria-expanded|tabindex|role|set:html|is:raw|define:vars)\s*=\s*'[^']*'", 'ATTRS'),
    # Schema.org @context/@type/@id values (keep — not body content)
    (r"""['"]@(?:context|type|id)['"]\s*:\s*['"][^'"]*['"]""", 'SCHKEY'),
    # URL-looking object values for keys that reference URLs (canonical, url, logo etc.)
    (r"""(?:canonical|url|logo|image|ogImage|twitterImage|sameAs)\s*:\s*['"][^'"]+['"]""", 'URLKV'),
]

SENTINEL_OPEN = '\uE000'
SENTINEL_CLOSE = '\uE001'

def build_combined_pattern():
    groups = []
    names = []
    for i, (pat, name) in enumerate(PROTECT_PATTERNS):
        groups.append(f'(?P<g{i}>{pat})')
        names.append(name)
    return re.compile('|'.join(groups), re.DOTALL | re.MULTILINE), names

COMBINED, NAMES = build_combined_pattern()

def mask(text: str):
    placeholders = []
    def repl(m):
        placeholders.append(m.group(0))
        idx = len(placeholders) - 1
        return f'{SENTINEL_OPEN}{idx}{SENTINEL_CLOSE}'
    masked = COMBINED.sub(repl, text)
    return masked, placeholders

def unmask(text: str, placeholders):
    # Use regex to match sentinel tokens and replace by index
    pattern = re.compile(re.escape(SENTINEL_OPEN) + r'(\d+)' + re.escape(SENTINEL_CLOSE))
    def rep(m):
        idx = int(m.group(1))
        if 0 <= idx < len(placeholders):
            return placeholders[idx]
        return m.group(0)
    return pattern.sub(rep, text)

def process_file(path: Path):
    orig = path.read_text(encoding='utf-8')
    masked, phs = mask(orig)
    # Safety check: sentinel chars shouldn't be in original
    if SENTINEL_OPEN in orig or SENTINEL_CLOSE in orig:
        print(f"WARN sentinel collision: {path}")
    converted = apply_word_map(masked)
    restored = unmask(converted, phs)
    # Post-check: no sentinel leaks
    if SENTINEL_OPEN in restored or SENTINEL_CLOSE in restored:
        print(f"ERROR sentinel leak in {path} — NOT writing")
        return -1
    if restored != orig:
        # Count changed lines for reporting
        oa = orig.splitlines()
        na = restored.splitlines()
        changes = sum(1 for a, b in zip(oa, na) if a != b) + abs(len(oa) - len(na))
        path.write_text(restored, encoding='utf-8')
        return changes
    return 0

def main():
    total_files = 0
    total_lines = 0
    for rel in TARGETS:
        p = ROOT / rel
        if not p.exists():
            print(f"MISSING: {rel}")
            continue
        c = process_file(p)
        if c > 0:
            total_files += 1
            total_lines += c
            print(f"CHANGED {c:>4} lines: {rel}")
        elif c == 0:
            print(f"no-op:           {rel}")
        else:
            print(f"SKIPPED (error): {rel}")
    print(f"\nSummary: {total_files} files changed, {total_lines} lines modified.")

if __name__ == '__main__':
    main()
